services:
  minutes:
    build: .
    container_name: minutes-app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/site.db
    volumes:
      - ./data:/data
      - ./static/images/custom:/app/static/images/custom
      - ./static/images/avatars:/app/static/images/avatars
    networks:
      - npm_default
    # ports:
    #   - "8085:8000"  # برای تست محلی در صورت نیاز

networks:
  npm_default:
    external: true


